const triviaConstants = {
  FETCH_TRIVIA_REQUEST: `FETCH_TRIVIA_REQUEST`,
  FETCH_TRIVIA_SUCCESS: `FETCH_TRIVIA_SUCCESS`,
  FETCH_TRIVIA_FAIL: `FETCH_TRIVIA_FAIL`,
};

export default triviaConstants;
